### ISSUE TITLE
Compute_expected.py: invalid syntax 

### ISSUE THREAD

**Issue by ZhangJiankun21** [mirnylab/cooltools#113]
Hi, I got this error when trying to install cooltools. 

`(hic) zhangjk@mgt  ~  21:37:31
$cooltools
Traceback (most recent call last):
  File "/share/home/zhangjk/anaconda2/envs/hic/bin/cooltools", line 11, in <module>
    load_entry_point('cooltools==0.3.0', 'console_scripts', 'cooltools')()
  File "/share/home/zhangjk/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/share/home/zhangjk/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/share/home/zhangjk/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/share/home/zhangjk/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/share/home/zhangjk/software/cooltools/cooltools/cli/__init__.py", line 50, in <module>
    from . import (
  File "/share/home/zhangjk/software/cooltools/cooltools/cli/compute_expected.py", line 131
    [{'chrom1': s1[0], 'chrom2': s2[0], **rec}
                                         ^
SyntaxError: invalid syntax
`

**Comment by golobor** [comment]
Hi,
It seems that you are using Python 2.7 . Unfortunately, we no longer
maintain the compatibility with Python 2.x. please let us know if you
encounter the same issue with Python 3!

Anton.
(typed on a phone, sorry for brevity and typos)

**Comment by ZhangJiankun21** [comment]
Problem solved. Thanks! :-)
