### ISSUE TITLE
down sample error: Found duplicate pixels

### ISSUE THREAD

**Issue by gspracklin** [mirnylab/cooltools#115]
I only see this error with some coolers, not others. 

@sergpolly - you saw something similar with the dotcaller any ideas? 

(base) spracklin@leavitt:/net/levsha/share/spracklin/HCT116_hic$ cooltools random-sample --frac 0.089 /net/levsha/share/lab/raoAiden2017/distiller-0.3.1_hg38/results/coolers_library_group/Unsynchronized.hg38.mapq_30.1000.mcool::/resolutions/100000 Unsynchronized.hg38.mapq_30_downsampled2.frac0.089.100000.mcool::/resolutions/100000
INFO:numexpr.utils:Note: NumExpr detected 36 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:cooler.create:Creating cooler at "Unsynchronized.hg38.mapq_30_downsampled2.frac0.089.100000.mcool::/resolutions/100000"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
Traceback (most recent call last):
  File "/home/spracklin/anaconda3/bin/cooltools", line 11, in <module>
    load_entry_point('cooltools', 'console_scripts', 'cooltools')()
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/spracklin/cooltools/cooltools/cli/random_sample.py", line 68, in random_sample
    frac=frac, exact=exact, chunksize=chunksize, map_func=map)
  File "/home/spracklin/cooltools/cooltools/sample.py", line 112, in sample_cooler
    out_clr_path, clr.bins()[:], iter(pipeline), ordered=True)
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/cooler/create/_create.py", line 925, in create_cooler
    lock=lock)
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/cooler/create/_create.py", line 577, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/cooler/create/_create.py", line 213, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/home/spracklin/anaconda3/lib/python3.7/site-packages/cooler/create/_ingest.py", line 307, in _validate_pixels
    raise BadInputError("Found duplicate pixels:\n{}".format(err.head().to_csv(sep='\t')))
cooler.create._ingest.BadInputError: Found duplicate pixels:
	bin1_id	bin2_id	count
846340	8943	8943	872
846341	8943	8944	371
846342	8943	8945	108
846343	8943	8946	102
846344	8943	8947	91

**Comment by gspracklin** [comment]
Issue is with older coolers. 

Re-zoomify from 1kb with cooler>=0.8.5
