### ISSUE TITLE
dot caller bug?

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooltools#27]
Job submitted with this script:
```
#!/bin/sh
# Grid Engine options (lines prefixed with #$)
#$ -cwd
#$ -N dots
#$ -l h_rt=12:00:00
#$ -l h_vmem=5G
#$ -pe sharedmem 8
#$ -j yes
#$ -V

cooltools call_dots $1 $2 -n 8 -v -s ../output/dots/$(basename $1)\_dotdata.hdf5 -o ../output/dots/$(basename $1)\_dots.txt
```
Output:
```
/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Tokenization took: 159.15 ms
Type conversion took: 58.95 ms
Parser memory cleanup took: 0.01 ms
Tokenization took: 349.91 ms
Type conversion took: 55.23 ms
Parser memory cleanup took: 0.01 ms
Tokenization took: 1.03 ms
Type conversion took: 0.90 ms
Parser memory cleanup took: 0.00 ms
../coolers/serum-KM.10000.cool and ../coolers/expected/serum-KM.10000.cool_expected.tsv passed cross-compatibility checks.
Traceback (most recent call last):
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/bin/cooltools", line 11, in <module>
    load_entry_point('cooltools==0.1.0', 'console_scripts', 'cooltools')()
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/cooltools/cli/call_dots.py", line 535, in call_dots
    nproc, verbose)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/cooltools/cli/call_dots.py", line 109, in scoring_step
    "{} tiles with w,p={},{} kernels".format(len(tiles),w,p))
NameError: name 'w' is not defined
```

Looks like a bug to me?..

**Comment by sergpolly** [comment]
I've also submitted a quick fix to the `develop` branch.

**Comment by Phlya** [comment]
OK, I guess it's solved then, thanks!
