### ISSUE TITLE
Trans eig output broken

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooltools#40]
Code like this is missing from trans eig:
https://github.com/mirnylab/cooltools/blob/34ba9a347010b614f483871baa74d29dbe23dd9d/cooltools/eigdecomp.py#L344-L348

It leads to this:
```
Traceback (most recent call last):
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/bin/cooltools", line 11, in <module>
    load_entry_point('cooltools==0.1.0', 'console_scripts', 'cooltools')()
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/Hi-C/lib/python3.6/site-packages/cooltools/cli/call_compartments.py", line 157, in call_compartments
    eigvals.to_csv(out_prefix + '.' + contact_type + '.lam.txt', sep='\t', index=False)
AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'
```

**Comment by sergpolly** [comment]
should be working now
