### ISSUE TITLE
 cooltools compute-saddle: matplotlib bar API change needs to be addressed

### ISSUE THREAD

**Issue by betulakgol** [mirnylab/cooltools#47]
The code `cooltools compute-saddle --strength --vmin -1 --vmax 1 --qrange 0.1 0.99 --contact-type trans --fig pdf --out-prefix U54-ESC4DN-FA-DpnII-2017524-R1_hg19_trans U54-ESC4DN-FA-DpnII-2017524-R1_hg19.100000.cool U54-ESC4DN-FA-DpnII-2017524-R1_hg19_trans.100000.trans.vecs.bedGraph U54-ESC4DN-FA-DpnII-2017524-R1_hg19.100000.expected.trans.tsv`  

The error `Traceback (most recent call last):
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/home/ba69w/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ba69w/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ba69w/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ba69w/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ba69w/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/cooltools/cli/compute_saddle.py", line 360, in compute_saddle
    heatmap_kws=heatmap_kws)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/cooltools/saddle.py", line 409, in saddleplot
    **margin_kws)
TypeError: bar() missing 1 required positional argument: 'x'`

Thank you!

**Comment by sergpolly** [comment]
I think i found it:
https://matplotlib.org/api/api_changes.html#bar-barh-no-longer-accepts-left-bottom-as-first-named-argument

@betulakgol  I think you updated to the latest/greatest matplotlib v3.something and they had some API changes there - precisely in that link above, about `bar/barh` functions ...

You could try downgrading your matplotlib to something matplotlib v2. something ...

**Comment by sergpolly** [comment]
@nvictus - sounds good!
@betulakgol are you up for an easy pull request contribution ?

**Comment by betulakgol** [comment]
@sergpolly Yes, sure.

**Comment by sergpolly** [comment]
+1

**Comment by sergpolly** [comment]
@betulakgol if you forgot how to make a PR, here are some instructions: https://github.com/mirnylab/distiller-nf/issues/126#issuecomment-462914139

if no longer interested, please let people know

**Comment by betulakgol** [comment]
@sergpolly I made the changes and pull request mirnylab.
