### ISSUE TITLE
Shared object missing with newest cooltools

### ISSUE THREAD

**Issue by DekkerBastiaan** [mirnylab/cooltools#59]
```
Traceback (most recent call last):
  File "/home/bd44w/lib/miniconda3/bin/cooltools", line 7, in <module>
    from cooltools.cli import cli
  File "/home/bd44w/lib/miniconda3/lib/python3.6/site-packages/cooltools/cli/__init__.py", line 50, in <module>
    from . import (
  File "/home/bd44w/lib/miniconda3/lib/python3.6/site-packages/cooltools/cli/compute_expected.py", line 5, in <module>
    from .. import expected
  File "/home/bd44w/lib/miniconda3/lib/python3.6/site-packages/cooltools/expected.py", line 16, in <module>
    import bioframe
  File "/home/bd44w/lib/miniconda3/lib/python3.6/site-packages/bioframe/__init__.py", line 4, in <module>
    from . import io
  File "/home/bd44w/lib/miniconda3/lib/python3.6/site-packages/bioframe/io/__init__.py", line 3, in <module>
    from . import formats
  File "/home/bd44w/lib/miniconda3/lib/python3.6/site-packages/bioframe/io/formats.py", line 15, in <module>
    import pysam
  File "/home/bd44w/lib/miniconda3/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

Tried to update OpenSSL but didn't work.

**Comment by golobor** [comment]
could your samtools be installed not via conda? I found this issue, which
may be helpful:
https://github.com/USDA-VS/vSNP/issues/5

The solution could be to uninstall samtools and install them via conda:

conda install -c bioconda pysam samtools


If you confirm this solution, than we should probably modify the install
requirements for cooltools

**Comment by golobor** [comment]
oh, i think i interpreted this error report completely wrong and this
solution will not work...

**Comment by nvictus** [comment]
Yeah, something is wrong with your pysam installation, though. In any case, we made the offending import inside bioframe non-global, so if you upgrade bioframe to v0.0.8, the error shouldn't get triggered (unless you use some functionality that requires pysam).

**Comment by DekkerBastiaan** [comment]
Actually samtools was the problem. After uninstalling and conda install it works again. 

Thanks for the quick response !

**Comment by betulakgol** [comment]
@nvictus @golobor 
``Traceback (most recent call last):
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/bin/cooltools", line 11, in <module>
    load_entry_point('cooltools==0.1.0', 'console_scripts', 'cooltools')()
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/cooltools/cli/call_compartments.py", line 164, in call_compartments
    value_field='E1')
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/bioframe/io/formats.py", line 435, in to_bigwig
    print_cmd=True)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site packages/bioframe/io/process.py", line 48, in run
    raise OSError("process failed: %d\n%s\n%s" % (p.returncode,  out.decode('utf-8'), err.decode('utf-8')))
OSError: process failed: 127
bedGraphToBigWig: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory``
It created .tsv and .txt files but not bigwig. I tried all above and reinstalling cooltools in a new env but did not work! Thank you!

**Comment by nvictus** [comment]
I think something is wrong with your kent source binary `bedGraphToBigWig`. Could you try re-installing it?
You can try either bioconda `ucsc-bedgraphtobigwig`, or on linux, just get the executable directly from: http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/

**Comment by betulakgol** [comment]
I installed different version of `bedGraphToBigWig`. 
Uninstalled  ucsc-bedgraphtobigwig-357-1 : 
`conda  uninstall ucsc-bedGraphToBigWig `
Installed ucsc-bedgraphtobigwig-366-0:
`conda  install  ucsc-bedGraphToBigWig==366-0`
Thanks.

**Comment by nvictus** [comment]
> Thanks.

Just to confirm: it worked?

**Comment by betulakgol** [comment]
Yes, it worked.
