### ISSUE TITLE
Dependencies develop branch

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooltools#74]
Hi,

Using your dev branch with cooler version >=0.8 fails with

```
Traceback (most recent call last):
  File "/home/ubuntu/data/miniconda3/envs/hicexplorer3/bin/cooltools", line 6, in <module>
    from cooltools.cli import cli
  File "/home/ubuntu/data/miniconda3/envs/hicexplorer3/lib/python3.6/site-packages/cooltools/cli/__init__.py", line 50, in <module>
    from . import (
  File "/home/ubuntu/data/miniconda3/envs/hicexplorer3/lib/python3.6/site-packages/cooltools/cli/compute_expected.py", line 5, in <module>
    from .. import expected
  File "/home/ubuntu/data/miniconda3/envs/hicexplorer3/lib/python3.6/site-packages/cooltools/expected.py", line 14, in <module>
    from cooler.contrib.dask import daskify
ModuleNotFoundError: No module named 'cooler.contrib'
```

With 0.7 it works. 

Best,

Joachim

**Comment by nvictus** [comment]
Thanks Joachim. Are you sure you've pulled the latest? That import line is supposed to be replaced:

https://github.com/mirnylab/cooltools/blob/develop/cooltools/expected.py#L14
